# Generated by Django 4.1.3 on 2022-11-24 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Palestrante',
        ),
        migrations.DeleteModel(
            name='TipoEvento',
        ),
    ]
