# Generated by Django 4.1.3 on 2022-11-25 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=5)),
                ('capacidade', models.IntegerField(default=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.local'),
        ),
    ]
