# Generated by Django 4.1.3 on 2022-11-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_local_evento_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='tipo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='local',
            name='descricao',
            field=models.CharField(default='', max_length=100),
        ),
    ]
