# Generated by Django 4.1.3 on 2022-11-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_evento_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='horario',
        ),
        migrations.AddField(
            model_name='evento',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='horario_fim',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='horario_inicio',
            field=models.TimeField(null=True),
        ),
    ]
