# Generated by Django 4.1.3 on 2022-11-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_evento_horario_evento_data_evento_horario_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
