# Generated by Django 4.1.3 on 2022-11-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_evento_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('idade', models.IntegerField()),
                ('evento', models.ManyToManyField(to='app.evento')),
            ],
        ),
    ]
